#!/bin/bash
# Gets a fresh Pharo 5.0 image and VM

# Load Pharo 5.0 image (without dependency on mktemp)

# stop the script if a single command fails
set -e
# DOWNLOADING THE LATEST PHARO 50 IMAGE =========================================
IMAGE_URL="http://files.pharo.org/image/50/latest.zip"
echo "Downloading the latest 50 Image:"
echo "    $IMAGE_URL"

rm -rf fresh.zip
rm -rf worker.*
rm -rf Pharo.*

curl $IMAGE_URL -o "fresh.zip" 

unzip -q fresh.zip -d .
rm -rf fresh fresh.zip

# Rename the default image name to worker.*
mv Pharo*.image Pharo.image
mv Pharo*.changes Pharo.changes

# Load VM
curl get.pharo.org/vm50 | bash
